Feature/open producten integration
Floris272/open-inwoner pull request #2
Opened 2024-09-17 14:30 UTC by Floris272

2024-09-23 10:41 UTC, swrichards requested changes
Ziet er goed uit. We kunnen het misschien nog wel even over de aanpak hebben (integratie met bestaande models versus een aparte mapping), maar dat heeft niet blockend te zijn.

2024-09-23 10:41 UTC, swrichards commented on src/open_inwoner/openproducten/clients.py
> +        return File.objects.create(original_filename=url.split("/")[-1], file=file)
Je zou kunnen zeggen dat deze methods hier niet thuis horen. Vanuit de "separation of concerns" gedacht, zou je zeggen dat de client uitsluitend bezig is met dingen uit de API halen. Vervolgens iets _doen_ met die gegevens gebeurt dan in-context. Met andere woorden, deze methodes zijn niet "algemeen" (in de context van de client) maar voor een specifieke context bedoeld (importeren naar  filer). Ik zou deze methodes in de import module plaatsen.

2024-09-23 10:41 UTC, swrichards commented on src/open_inwoner/openproducten/producttypes_imports.py
> +        generate a Product for every ProductType in the Open Producten API
Conventie voor docstrings is volledige zinnen (caps, leestekens):

```suggestion
        Generate a Product for every ProductType in the Open Producten API.
```

2024-09-23 10:41 UTC, swrichards commented on src/open_inwoner/pdc/models/product.py
Voor de volledigheid: een belangrijke vraag hier is: willen we ondersteuning behouden voor het scenario waarin je geen OpenProducten gebruikt? (In de praktijk is het antwoord vrijwel zeker ja).

Dat is wat meer werk: dan wil je de mapping waarschijnlijk apart houden (geen OpenProduct mixin, maar aparte models die mappen van de OIP models naar OpenProduct UUIDs). Gezien het hier denk ik vooral om de proof-of-concept gaat, is dit pad voor nu prima, maar iets om ons bewust van te zijn.

2024-09-23 10:41 UTC, swrichards commented on src/open_inwoner/openproducten/producttypes_imports.py
> +class OpenProductenImporter:
Je kan hier [een abstract base class](https://docs.python.org/3.11/library/abc.html) van maken, gezien het niet de bedoeling is dat deze direct geinstantieerd wordt.

2024-09-23 10:41 UTC, swrichards commented on src/open_inwoner/openproducten/producttypes_imports.py
In deze functies zouden type hints voor de argumenten de leesbaarheid vergroten, om makkelijker te zien waar je Django models verwacht en waar API models.

2024-09-23 10:41 UTC, swrichards commented on src/open_inwoner/openproducten/producttypes_imports.py
> +class ProductTypeImporter(OpenProductenImporter):
Aanpak is hier op zich prima. Er is sprake van recursiviteit (de product type relations maken zelf weer product types aan) en aardig wat nesting, bij grote datasets zou dat problematisch kunnen worden maar we hebben het hier niet over duizenden rows.

2024-09-23 10:41 UTC, swrichards commented on src/open_inwoner/openproducten/producttypes_imports.py
> +    def _handle_relations(self, product_type, product_type_instance):
De enige gedachte die me bekruipt bij de recursiviteit en de management van relations is of er gevallen denkbaar zijn waar waar twee product types naar elkaar verwijzen, en is er dan een gevaar voor een inifnite loop c.q. recursion? (Alternatief zou zijn om _eerst_ alle `ProductType` objecten aan te maken met uuid en dummy velden, en dan pas de inhoudelijke veleden te syncen). Maar goed, dat is wellicht een edge case waar we nu nog geen rekening mee hoeven te houden (maar zou een aardige test case zijn).

2024-09-23 10:41 UTC, swrichards commented on src/open_inwoner/openproducten/producttypes_imports.py
> +        self.product_types = self.client.fetch_producttypes_no_cache()
Geen pagination?

2024-09-26 15:08 UTC, Floris272 commented on src/open_inwoner/pdc/models/product.py
Besproken, mapping zal mogelijk nog worden toegevoegd mocht er tijd over zijn.

2024-10-03 13:58 UTC, Floris272 commented on src/open_inwoner/openproducten/producttypes_imports.py
> +    def _handle_relations(self, product_type, product_type_instance):
Afgehandelde product typen worden bijgehouden en worden niet nog een keer geupdate. Zal een test aan de volgende pr (met alle testen) toevoegen.

2024-10-03 14:40 UTC, swrichards requested changes

2024-10-03 14:40 UTC, swrichards commented on src/open_inwoner/openproducten/clients.py
> +        return File.objects.create(original_filename=url.split("/")[-1], file=file)
Ik blijf het niet helemaal correct vinden dat deze functies hier zitten:

1. Er zit weinig client-specifieke functionaliteit in (de URL komt van de parameters, het fetchen van een URL kan ook wherever het nodig is)
2. Er zijn side-effects: er worden models aangemaakt, dat lijkt me niet passen voor een client.

2024-10-03 14:40 UTC, swrichards commented on src/open_inwoner/openproducten/producttypes_imports.py
> +class OpenProductenImporter:
Correctie op mijn eerdere comment: het is niet echt een abc, want de child classes implementeren geen parent methods, maar meer een `Mixin`. Ik denk dat `OpenProductImporterMixin` een betere naam zou zijn, omdat je daarmee aangeeft dat deze class niet bedoeld is om onafhankelijk te instantieren.

2024-10-03 15:14 UTC, Floris272 commented on src/open_inwoner/openproducten/clients.py
> +        return File.objects.create(original_filename=url.split("/")[-1], file=file)
get_image en get_file zijn verplaatst naar de OpenProductenImporter in [567e7e4](https://github.com/Floris272/open-inwoner/pull/2/commits/567e7e4035fdbb3d1c0cff84e65e027619ded420)

2024-10-04 13:44 UTC, merged