Feature/open producten integration tests
Floris272/open-inwoner pull request #3
Opened 2024-10-07 10:55 UTC by Floris272

2024-10-08 08:45 UTC, swrichards requested changes

2024-10-08 08:45 UTC, swrichards commented on src/open_inwoner/openproducten/tests/helpers.py
> +    return DjangoFile(temp_file)
Goed om een context manager te gebruiken voor temp files, zodat Python ze netjes kan opruimen na afloop:

```suggestion
    with NamedTemporaryFile(delete=True) as temp_file:
        temp_file.write(content)
        return DjangoFile(temp_file)
```

2024-10-08 08:45 UTC, swrichards commented on src/open_inwoner/openproducten/tests/test_category_importer.py
> +        patch(
Kan deze niet gewoon als:

```
@patch(...)
class TestCategoryImporter
```

..?

2024-10-08 08:45 UTC, swrichards commented on src/open_inwoner/openproducten/tests/test_category_importer.py
> +                uuid = str(uuid4())
De orm zou ook direct moet het uuid object overweg moeten kunnen, zonder eerst `str` te doen.

2024-10-08 08:45 UTC, swrichards commented on src/open_inwoner/openproducten/tests/test_product_type_importer.py
> +        )
Als de volgorde er niet toe doet zijn sets leesbaarder:

```suggestion
        self.assertEqual(
            {obj.open_producten_uuid for obj in updated},
            {obj.open_producten_uuid for obj in all_objects},
        )
```

2024-10-08 08:45 UTC, swrichards commented on src/open_inwoner/openproducten/tests/test_product_type_importer.py
> +        )
(ook elders)

2024-10-08 08:45 UTC, swrichards commented on src/open_inwoner/openproducten/tests/test_product_type_importer.py
> +        self.assertEqual(pdc_models.Question.objects.count(), 1)
Deze zouden dus ook gelijk moeten zijn _voor_ de tweede import, je zou de twee calls in een `for _ in range(2)` kunnen wrappen om deze asserts tweemaal te doen.

2024-10-08 08:45 UTC, swrichards commented on src/open_inwoner/openproducten/tests/helpers.py
> +        pdc_models.Question.objects.first(),
`.first()` voelt een beetje fragiel: dit hangt af van context buiten deze functie c.q. de test setup, en is daarmee wat moeilijk te parsen. Is het niet beter om gewoon alle objects te returnen, en dat je test faalt als er meer dan 1 zijn? Dan is de context lokaal bij het aanroepen bekend.

2024-10-08 12:55 UTC, Floris272 commented on src/open_inwoner/openproducten/tests/helpers.py
> +    return DjangoFile(temp_file)
Met een context manager ontstaat een error als een bestand later wordt aangemaakt in de media_root.

Om alle bestanden te verwijderen is nu de MEDIA_ROOT overschreven zodat het na de testen kan worden verwijderd.

in `TestOpenProductenImporter` wordt `create_temp_file` direct aangeroepen waardoor de bestanden niet uit `/tmp/` worden verwijderd. daarom wordt dit nu gedaan in de teardown.

in `TestProductTypeImporter` wordt `create_file_instance` aangeroepen waardoor ze wel worden verwijderd uit `/tmp/`.

Daarnaast hebben een aantal testen in `TestProductTypeImporter` een integrity error in de post_teardown, waarschijnlijk omdat het bestand al wel weg is. Dit is nu opgelost door alle ProductFiles alvast te verwijderen in de tearDown, geen idee waarom dit wel werkt.

2024-10-09 08:58 UTC, swrichards commented on src/open_inwoner/openproducten/tests/helpers.py
> +    return DjangoFile(temp_file)
Zou je kunnen proberen om, ipv een `DjangoFile`, [een `ContentFile` te gebruiken](https://docs.djangoproject.com/en/5.1/ref/files/file/#the-contentfile-class)? Dan zit alles in-memory en heb je het hele gedonder niet van die tempfiles.

2024-10-09 09:01 UTC, swrichards commented on src/open_inwoner/openproducten/tests/helpers.py
> +    return DjangoFile(temp_file)
(De constructie waarbij je `MEDIA_ROOT` naar een bekenede in-repo dir verwijst en schoonmaakt na het testen is verder prima).

2024-10-09 09:58 UTC, Floris272 commented on src/open_inwoner/openproducten/tests/helpers.py
> +    return DjangoFile(temp_file)
Aha, ik kan ook gewoon de content diect in de django file stoppen inplaats van in eerst de temp file. Door dit te gebruiken word de media root niet eens gevult waardoor de media override ook niet meer nodig is.

2024-10-09 10:45 UTC, swrichards commented on src/open_inwoner/openproducten/tests/helpers.py
> +    return DjangoFile(temp_file)
Nog makkelijker idd.

2024-10-09 10:45 UTC, swrichards approved these changes

2024-10-09 12:34 UTC, merged